#############################################################################
# Makefile for building: nTrainer
# Generated by qmake (2.01a) (Qt 4.6.3) on: ?? ????. 1 01:15:20 2010
# Project:  nTrainer.pro
# Template: app
# Command: /usr/bin/qmake -spec /usr/share/qt4/mkspecs/linux-g++ -unix CONFIG+=debug -o Makefile nTrainer.pro
#############################################################################

####### Compiler, tools and options

CC            = gcc
CXX           = g++
DEFINES       = -DQT_GUI_LIB -DQT_CORE_LIB -DQT_SHARED
CLIFLAGS      = -pipe -g -Wall -W -DNDEBUG -D_REENTRANT -O3
CFLAGS        = $(CLIFLAGS) $(DEFINES)
CXXFLAGS      = $(CLIFLAGS) $(DEFINES)
INCPATH       = -I/usr/share/qt4/mkspecs/linux-g++ -I. -I/usr/include/qt4/QtCore -I/usr/include/qt4/QtGui -I/usr/include/qt4 -I. -I.
LINK          = g++
LFLAGS        = -Wl,-rpath,/usr/lib64/qt4
LIBS          = $(SUBLIBS)  -L/usr/lib64/qt4 -lQtGui -L/usr/lib64 -L/usr/lib64/qt4 -L/usr/X11R6/lib -lQtCore -lgthread-2.0 -lrt -lglib-2.0 -lpthread
AR            = ar cqs
RANLIB        =
QMAKE         = /usr/bin/qmake
TAR           = tar -cf
COMPRESS      = gzip -9f
COPY          = cp -f
SED           = sed
COPY_FILE     = $(COPY)
COPY_DIR      = $(COPY) -r
STRIP         = strip
INSTALL_FILE  = install -m 644 -p
INSTALL_DIR   = $(COPY_DIR)
INSTALL_PROGRAM = install -m 755 -p
DEL_FILE      = rm -f
SYMLINK       = ln -f -s
DEL_DIR       = rmdir
MOVE          = mv -f
CHK_DIR_EXISTS= test -d
MKDIR         = mkdir -p

####### Output directory

OBJECTS_DIR   = ./

####### Files

SOURCES       = main.cpp \
		ntrain.cpp \
		bpnlayer.cpp \
		bpn.cpp moc_ntrain.cpp
OBJECTS       = main.o \
		ntrain.o \
		bpnlayer.o \
		bpn.o \
		moc_ntrain.o
DIST          = /usr/share/qt4/mkspecs/common/g++.conf \
		/usr/share/qt4/mkspecs/common/unix.conf \
		/usr/share/qt4/mkspecs/common/linux.conf \
		/usr/share/qt4/mkspecs/qconfig.pri \
		/usr/share/qt4/mkspecs/features/qt_functions.prf \
		/usr/share/qt4/mkspecs/features/qt_config.prf \
		/usr/share/qt4/mkspecs/features/exclusive_builds.prf \
		/usr/share/qt4/mkspecs/features/default_pre.prf \
		/usr/share/qt4/mkspecs/features/debug.prf \
		/usr/share/qt4/mkspecs/features/default_post.prf \
		/usr/share/qt4/mkspecs/features/warn_on.prf \
		/usr/share/qt4/mkspecs/features/qt.prf \
		/usr/share/qt4/mkspecs/features/unix/thread.prf \
		/usr/share/qt4/mkspecs/features/moc.prf \
		/usr/share/qt4/mkspecs/features/resources.prf \
		/usr/share/qt4/mkspecs/features/uic.prf \
		/usr/share/qt4/mkspecs/features/yacc.prf \
		/usr/share/qt4/mkspecs/features/lex.prf \
		/usr/share/qt4/mkspecs/features/include_source_dir.prf \
		nTrainer.pro
QMAKE_TARGET  = nTrainer
DESTDIR       =
TARGET        = nTrainer

first: all
####### Implicit rules

.SUFFIXES: .o .c .cpp .cc .cxx .C

.cpp.o:
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o "$@" "$<"

.cc.o:
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o "$@" "$<"

.cxx.o:
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o "$@" "$<"

.C.o:
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o "$@" "$<"

.c.o:
	$(CC) -c $(CFLAGS) $(INCPATH) -o "$@" "$<"

####### Build rules

all: Makefile $(TARGET)

$(TARGET): ui_ntrain.h $(OBJECTS)
	$(LINK) $(LFLAGS) -o $(TARGET) $(OBJECTS) $(OBJCOMP) $(LIBS)

Makefile: nTrainer.pro  /usr/share/qt4/mkspecs/linux-g++/qmake.conf /usr/share/qt4/mkspecs/common/g++.conf \
		/usr/share/qt4/mkspecs/common/unix.conf \
		/usr/share/qt4/mkspecs/common/linux.conf \
		/usr/share/qt4/mkspecs/qconfig.pri \
		/usr/share/qt4/mkspecs/features/qt_functions.prf \
		/usr/share/qt4/mkspecs/features/qt_config.prf \
		/usr/share/qt4/mkspecs/features/exclusive_builds.prf \
		/usr/share/qt4/mkspecs/features/default_pre.prf \
		/usr/share/qt4/mkspecs/features/debug.prf \
		/usr/share/qt4/mkspecs/features/default_post.prf \
		/usr/share/qt4/mkspecs/features/warn_on.prf \
		/usr/share/qt4/mkspecs/features/qt.prf \
		/usr/share/qt4/mkspecs/features/unix/thread.prf \
		/usr/share/qt4/mkspecs/features/moc.prf \
		/usr/share/qt4/mkspecs/features/resources.prf \
		/usr/share/qt4/mkspecs/features/uic.prf \
		/usr/share/qt4/mkspecs/features/yacc.prf \
		/usr/share/qt4/mkspecs/features/lex.prf \
		/usr/share/qt4/mkspecs/features/include_source_dir.prf \
		/usr/lib64/qt4/libQtGui.prl \
		/usr/lib64/qt4/libQtCore.prl
	$(QMAKE) -spec /usr/share/qt4/mkspecs/linux-g++ -unix CONFIG+=debug -o Makefile nTrainer.pro
/usr/share/qt4/mkspecs/common/g++.conf:
/usr/share/qt4/mkspecs/common/unix.conf:
/usr/share/qt4/mkspecs/common/linux.conf:
/usr/share/qt4/mkspecs/qconfig.pri:
/usr/share/qt4/mkspecs/features/qt_functions.prf:
/usr/share/qt4/mkspecs/features/qt_config.prf:
/usr/share/qt4/mkspecs/features/exclusive_builds.prf:
/usr/share/qt4/mkspecs/features/default_pre.prf:
/usr/share/qt4/mkspecs/features/debug.prf:
/usr/share/qt4/mkspecs/features/default_post.prf:
/usr/share/qt4/mkspecs/features/warn_on.prf:
/usr/share/qt4/mkspecs/features/qt.prf:
/usr/share/qt4/mkspecs/features/unix/thread.prf:
/usr/share/qt4/mkspecs/features/moc.prf:
/usr/share/qt4/mkspecs/features/resources.prf:
/usr/share/qt4/mkspecs/features/uic.prf:
/usr/share/qt4/mkspecs/features/yacc.prf:
/usr/share/qt4/mkspecs/features/lex.prf:
/usr/share/qt4/mkspecs/features/include_source_dir.prf:
/usr/lib64/qt4/libQtGui.prl:
/usr/lib64/qt4/libQtCore.prl:
qmake:  FORCE
	@$(QMAKE) -spec /usr/share/qt4/mkspecs/linux-g++ -unix CONFIG+=debug -o Makefile nTrainer.pro

dist:
	@$(CHK_DIR_EXISTS) .tmp/nTrainer1.0.0 || $(MKDIR) .tmp/nTrainer1.0.0
	$(COPY_FILE) --parents $(SOURCES) $(DIST) .tmp/nTrainer1.0.0/ && $(COPY_FILE) --parents ntrain.h bpnlayer.h bpn.h .tmp/nTrainer1.0.0/ && $(COPY_FILE) --parents main.cpp ntrain.cpp bpnlayer.cpp bpn.cpp .tmp/nTrainer1.0.0/ && $(COPY_FILE) --parents ntrain.ui .tmp/nTrainer1.0.0/ && (cd `dirname .tmp/nTrainer1.0.0` && $(TAR) nTrainer1.0.0.tar nTrainer1.0.0 && $(COMPRESS) nTrainer1.0.0.tar) && $(MOVE) `dirname .tmp/nTrainer1.0.0`/nTrainer1.0.0.tar.gz . && $(DEL_FILE) -r .tmp/nTrainer1.0.0


clean:compiler_clean
	-$(DEL_FILE) $(OBJECTS)
	-$(DEL_FILE) *~ core *.core
	-$(DEL_FILE) ntrain-cli.o

####### Sub-libraries

distclean: clean
	-$(DEL_FILE) $(TARGET) ntrain-cli


check: first

mocclean: compiler_moc_header_clean compiler_moc_source_clean

mocables: compiler_moc_header_make_all compiler_moc_source_make_all

compiler_moc_header_make_all: moc_ntrain.cpp
compiler_moc_header_clean:
	-$(DEL_FILE) moc_ntrain.cpp
moc_ntrain.cpp: bpn.h \
		bpnlayer.h \
		ntrain.h
	/usr/bin/moc $(DEFINES) $(INCPATH) ntrain.h -o moc_ntrain.cpp

compiler_rcc_make_all:
compiler_rcc_clean:
compiler_image_collection_make_all: qmake_image_collection.cpp
compiler_image_collection_clean:
	-$(DEL_FILE) qmake_image_collection.cpp
compiler_moc_source_make_all:
compiler_moc_source_clean:
compiler_uic_make_all: ui_ntrain.h
compiler_uic_clean:
	-$(DEL_FILE) ui_ntrain.h
ui_ntrain.h: ntrain.ui
	/usr/bin/uic ntrain.ui -o ui_ntrain.h

compiler_yacc_decl_make_all:
compiler_yacc_decl_clean:
compiler_yacc_impl_make_all:
compiler_yacc_impl_clean:
compiler_lex_make_all:
compiler_lex_clean:
compiler_clean: compiler_moc_header_clean compiler_uic_clean

####### Compile

main.o: main.cpp ntrain.h \
		bpn.h \
		bpnlayer.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o main.o main.cpp

ntrain.o: ntrain.cpp ntrain.h \
		bpn.h \
		bpnlayer.h \
		ui_ntrain.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o ntrain.o ntrain.cpp

bpnlayer.o: bpnlayer.cpp bpnlayer.h
	$(CXX) -c $(CLIFLAGS) -o bpnlayer.o bpnlayer.cpp

bpn.o: bpn.cpp bpn.h \
		bpnlayer.h
	$(CXX) -c $(CLIFLAGS) -o bpn.o bpn.cpp

moc_ntrain.o: moc_ntrain.cpp
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_ntrain.o moc_ntrain.cpp

####### Install

install:   FORCE

uninstall:   FORCE

FORCE:

####### CLI

ntrain-cli.o: bpn.h
	$(CXX) -c $(CLIFLAGS) -o ntrain-cli.o ntrain-cli.cpp

cli: ntrain-cli.o bpn.o bpnlayer.o
	$(CXX) $(CLIFLAGS) -o ntrain-cli ntrain-cli.o bpn.o bpnlayer.o -lpthread
