#############################################################################
# Makefile for building: nTrainer
# Generated by qmake (2.01a) (Qt 4.5.1) on: ?? ??? 10 19:54:32 2009
# Project:  nTrainer.pro
# Template: app
# Command: /opt/qtsdk-2009.02/qt/bin/qmake -spec /opt/qtsdk-2009.02/qt/mkspecs/linux-g++-64 -unix CONFIG+=debug -o Makefile nTrainer.pro
#############################################################################

####### Compiler, tools and options

CC            = gcc
CXX           = g++
DEFINES       = -DQT_GUI_LIB -DQT_CORE_LIB -DQT_SHARED
CFLAGS        = -m64 -pipe -g -Wall -W -D_REENTRANT $(DEFINES)
CXXFLAGS      = -m64 -pipe -g -Wall -W -D_REENTRANT $(DEFINES)
INCPATH       = -I/opt/qtsdk-2009.02/qt/mkspecs/linux-g++-64 -I. -I/opt/qtsdk-2009.02/qt/include/QtCore -I/opt/qtsdk-2009.02/qt/include/QtGui -I/opt/qtsdk-2009.02/qt/include -I. -I.
LINK          = g++
LFLAGS        = -m64 -Wl,-rpath,/opt/qtsdk-2009.02/qt/lib
LIBS          = $(SUBLIBS)  -L/opt/qtsdk-2009.02/qt/lib -lQtGui -L/opt/qtsdk-2009.02/qt/lib -L/usr/X11R6/lib64 -pthread -lfreetype -lgobject-2.0 -lSM -lICE -pthread -pthread -lXrender -lfontconfig -lXext -lX11 -lQtCore -lm -pthread -lgthread-2.0 -lrt -lglib-2.0 -ldl -lpthread
AR            = ar cqs
RANLIB        = 
QMAKE         = /opt/qtsdk-2009.02/qt/bin/qmake
TAR           = tar -cf
COMPRESS      = gzip -9f
COPY          = cp -f
SED           = sed
COPY_FILE     = $(COPY)
COPY_DIR      = $(COPY) -r
INSTALL_FILE  = install -m 644 -p
INSTALL_DIR   = $(COPY_DIR)
INSTALL_PROGRAM = install -m 755 -p
DEL_FILE      = rm -f
SYMLINK       = ln -sf
DEL_DIR       = rmdir
MOVE          = mv -f
CHK_DIR_EXISTS= test -d
MKDIR         = mkdir -p

####### Output directory

OBJECTS_DIR   = ./

####### Files

SOURCES       = main.cpp \
		ntrain.cpp \
		bpnlayer.cpp \
		bpn.cpp moc_ntrain.cpp
OBJECTS       = main.o \
		ntrain.o \
		bpnlayer.o \
		bpn.o \
		moc_ntrain.o
DIST          = /opt/qtsdk-2009.02/qt/mkspecs/common/g++.conf \
		/opt/qtsdk-2009.02/qt/mkspecs/common/unix.conf \
		/opt/qtsdk-2009.02/qt/mkspecs/common/linux.conf \
		/opt/qtsdk-2009.02/qt/mkspecs/qconfig.pri \
		/opt/qtsdk-2009.02/qt/mkspecs/features/qt_functions.prf \
		/opt/qtsdk-2009.02/qt/mkspecs/features/qt_config.prf \
		/opt/qtsdk-2009.02/qt/mkspecs/features/exclusive_builds.prf \
		/opt/qtsdk-2009.02/qt/mkspecs/features/default_pre.prf \
		/opt/qtsdk-2009.02/qt/mkspecs/features/debug.prf \
		/opt/qtsdk-2009.02/qt/mkspecs/features/default_post.prf \
		/opt/qtsdk-2009.02/qt/mkspecs/features/warn_on.prf \
		/opt/qtsdk-2009.02/qt/mkspecs/features/qt.prf \
		/opt/qtsdk-2009.02/qt/mkspecs/features/unix/thread.prf \
		/opt/qtsdk-2009.02/qt/mkspecs/features/moc.prf \
		/opt/qtsdk-2009.02/qt/mkspecs/features/resources.prf \
		/opt/qtsdk-2009.02/qt/mkspecs/features/uic.prf \
		/opt/qtsdk-2009.02/qt/mkspecs/features/yacc.prf \
		/opt/qtsdk-2009.02/qt/mkspecs/features/lex.prf \
		/opt/qtsdk-2009.02/qt/mkspecs/features/include_source_dir.prf \
		nTrainer.pro
QMAKE_TARGET  = nTrainer
DESTDIR       = 
TARGET        = nTrainer

first: all
####### Implicit rules

.SUFFIXES: .o .c .cpp .cc .cxx .C

.cpp.o:
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o "$@" "$<"

.cc.o:
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o "$@" "$<"

.cxx.o:
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o "$@" "$<"

.C.o:
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o "$@" "$<"

.c.o:
	$(CC) -c $(CFLAGS) $(INCPATH) -o "$@" "$<"

####### Build rules

all: Makefile $(TARGET)

$(TARGET): ui_ntrain.h $(OBJECTS)  
	$(LINK) $(LFLAGS) -o $(TARGET) $(OBJECTS) $(OBJCOMP) $(LIBS)

Makefile: nTrainer.pro  /opt/qtsdk-2009.02/qt/mkspecs/linux-g++-64/qmake.conf /opt/qtsdk-2009.02/qt/mkspecs/common/g++.conf \
		/opt/qtsdk-2009.02/qt/mkspecs/common/unix.conf \
		/opt/qtsdk-2009.02/qt/mkspecs/common/linux.conf \
		/opt/qtsdk-2009.02/qt/mkspecs/qconfig.pri \
		/opt/qtsdk-2009.02/qt/mkspecs/features/qt_functions.prf \
		/opt/qtsdk-2009.02/qt/mkspecs/features/qt_config.prf \
		/opt/qtsdk-2009.02/qt/mkspecs/features/exclusive_builds.prf \
		/opt/qtsdk-2009.02/qt/mkspecs/features/default_pre.prf \
		/opt/qtsdk-2009.02/qt/mkspecs/features/debug.prf \
		/opt/qtsdk-2009.02/qt/mkspecs/features/default_post.prf \
		/opt/qtsdk-2009.02/qt/mkspecs/features/warn_on.prf \
		/opt/qtsdk-2009.02/qt/mkspecs/features/qt.prf \
		/opt/qtsdk-2009.02/qt/mkspecs/features/unix/thread.prf \
		/opt/qtsdk-2009.02/qt/mkspecs/features/moc.prf \
		/opt/qtsdk-2009.02/qt/mkspecs/features/resources.prf \
		/opt/qtsdk-2009.02/qt/mkspecs/features/uic.prf \
		/opt/qtsdk-2009.02/qt/mkspecs/features/yacc.prf \
		/opt/qtsdk-2009.02/qt/mkspecs/features/lex.prf \
		/opt/qtsdk-2009.02/qt/mkspecs/features/include_source_dir.prf \
		/opt/qtsdk-2009.02/qt/lib/libQtGui.prl \
		/opt/qtsdk-2009.02/qt/lib/libQtCore.prl
	$(QMAKE) -spec /opt/qtsdk-2009.02/qt/mkspecs/linux-g++-64 -unix CONFIG+=debug -o Makefile nTrainer.pro
/opt/qtsdk-2009.02/qt/mkspecs/common/g++.conf:
/opt/qtsdk-2009.02/qt/mkspecs/common/unix.conf:
/opt/qtsdk-2009.02/qt/mkspecs/common/linux.conf:
/opt/qtsdk-2009.02/qt/mkspecs/qconfig.pri:
/opt/qtsdk-2009.02/qt/mkspecs/features/qt_functions.prf:
/opt/qtsdk-2009.02/qt/mkspecs/features/qt_config.prf:
/opt/qtsdk-2009.02/qt/mkspecs/features/exclusive_builds.prf:
/opt/qtsdk-2009.02/qt/mkspecs/features/default_pre.prf:
/opt/qtsdk-2009.02/qt/mkspecs/features/debug.prf:
/opt/qtsdk-2009.02/qt/mkspecs/features/default_post.prf:
/opt/qtsdk-2009.02/qt/mkspecs/features/warn_on.prf:
/opt/qtsdk-2009.02/qt/mkspecs/features/qt.prf:
/opt/qtsdk-2009.02/qt/mkspecs/features/unix/thread.prf:
/opt/qtsdk-2009.02/qt/mkspecs/features/moc.prf:
/opt/qtsdk-2009.02/qt/mkspecs/features/resources.prf:
/opt/qtsdk-2009.02/qt/mkspecs/features/uic.prf:
/opt/qtsdk-2009.02/qt/mkspecs/features/yacc.prf:
/opt/qtsdk-2009.02/qt/mkspecs/features/lex.prf:
/opt/qtsdk-2009.02/qt/mkspecs/features/include_source_dir.prf:
/opt/qtsdk-2009.02/qt/lib/libQtGui.prl:
/opt/qtsdk-2009.02/qt/lib/libQtCore.prl:
qmake:  FORCE
	@$(QMAKE) -spec /opt/qtsdk-2009.02/qt/mkspecs/linux-g++-64 -unix CONFIG+=debug -o Makefile nTrainer.pro

dist: 
	@$(CHK_DIR_EXISTS) .tmp/nTrainer1.0.0 || $(MKDIR) .tmp/nTrainer1.0.0 
	$(COPY_FILE) --parents $(SOURCES) $(DIST) .tmp/nTrainer1.0.0/ && $(COPY_FILE) --parents ntrain.h bpnlayer.h bpn.h .tmp/nTrainer1.0.0/ && $(COPY_FILE) --parents main.cpp ntrain.cpp bpnlayer.cpp bpn.cpp .tmp/nTrainer1.0.0/ && $(COPY_FILE) --parents ntrain.ui .tmp/nTrainer1.0.0/ && (cd `dirname .tmp/nTrainer1.0.0` && $(TAR) nTrainer1.0.0.tar nTrainer1.0.0 && $(COMPRESS) nTrainer1.0.0.tar) && $(MOVE) `dirname .tmp/nTrainer1.0.0`/nTrainer1.0.0.tar.gz . && $(DEL_FILE) -r .tmp/nTrainer1.0.0


clean:compiler_clean 
	-$(DEL_FILE) $(OBJECTS)
	-$(DEL_FILE) *~ core *.core


####### Sub-libraries

distclean: clean
	-$(DEL_FILE) $(TARGET) 
	-$(DEL_FILE) Makefile


mocclean: compiler_moc_header_clean compiler_moc_source_clean

mocables: compiler_moc_header_make_all compiler_moc_source_make_all

compiler_moc_header_make_all: moc_ntrain.cpp
compiler_moc_header_clean:
	-$(DEL_FILE) moc_ntrain.cpp
moc_ntrain.cpp: bpn.h \
		bpnlayer.h \
		ntrain.h
	/opt/qtsdk-2009.02/qt/bin/moc $(DEFINES) $(INCPATH) ntrain.h -o moc_ntrain.cpp

compiler_rcc_make_all:
compiler_rcc_clean:
compiler_image_collection_make_all: qmake_image_collection.cpp
compiler_image_collection_clean:
	-$(DEL_FILE) qmake_image_collection.cpp
compiler_moc_source_make_all:
compiler_moc_source_clean:
compiler_uic_make_all: ui_ntrain.h
compiler_uic_clean:
	-$(DEL_FILE) ui_ntrain.h
ui_ntrain.h: ntrain.ui
	/opt/qtsdk-2009.02/qt/bin/uic ntrain.ui -o ui_ntrain.h

compiler_yacc_decl_make_all:
compiler_yacc_decl_clean:
compiler_yacc_impl_make_all:
compiler_yacc_impl_clean:
compiler_lex_make_all:
compiler_lex_clean:
compiler_clean: compiler_moc_header_clean compiler_uic_clean 

####### Compile

main.o: main.cpp ntrain.h \
		bpn.h \
		bpnlayer.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o main.o main.cpp

ntrain.o: ntrain.cpp ntrain.h \
		bpn.h \
		bpnlayer.h \
		ui_ntrain.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o ntrain.o ntrain.cpp

bpnlayer.o: bpnlayer.cpp bpnlayer.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o bpnlayer.o bpnlayer.cpp

bpn.o: bpn.cpp bpn.h \
		bpnlayer.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o bpn.o bpn.cpp

moc_ntrain.o: moc_ntrain.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_ntrain.o moc_ntrain.cpp

####### Install

install:   FORCE

uninstall:   FORCE

FORCE:

